/*!


*/

use Display;
use {context, gl};

/// Severity of a debug message.
#[deriving(Clone, Copy, Show, FromPrimitive, PartialEq, Eq)]
#[repr(u32)]
pub enum Severity {
    /// Anything that isn't an error or performance issue.
    Notification = gl::DEBUG_SEVERITY_NOTIFICATION,

    /// Redundant state change performance warning, or unimportant undefined behavior.
    Low = gl::DEBUG_SEVERITY_LOW,

    /// Major performance warnings, shader compilation/linking warnings,
    /// or the use of deprecated functionality.
    Medium = gl::DEBUG_SEVERITY_MEDIUM,

    /// All OpenGL Errors, shader compilation/linking errors,
    /// or highly-dangerous undefined behavior.
    High = gl::DEBUG_SEVERITY_HIGH,
}

/// Source of a debug message.
#[deriving(Clone, Copy, Show, FromPrimitive)]
#[repr(u32)]
pub enum Source {
    /// Calls to the OpenGL API.
    Api = gl::DEBUG_SOURCE_API,

    /// Calls to a window-system API.
    WindowSystem = gl::DEBUG_SOURCE_WINDOW_SYSTEM,

    /// A compiler for a shading language.
    ShaderCompiler = gl::DEBUG_SOURCE_SHADER_COMPILER,

    /// An application associated with Openctxt.gl.
    ThirdParty = gl::DEBUG_SOURCE_THIRD_PARTY,

    /// Explicitely generated by Glium or the application.
    ///
    /// This should never happen, but is included here for completeness.
    Application = gl::DEBUG_SOURCE_APPLICATION,

    ///
    OtherSource = gl::DEBUG_SOURCE_OTHER,
}

/// Type of a debug message.
#[deriving(Clone, Copy, Show, FromPrimitive)]
#[repr(u32)]
pub enum MessageType {
    /// An error, typically from the API
    Error = gl::DEBUG_TYPE_ERROR,
    /// Some behavior marked deprecated has been used
    DeprecatedBehavior = gl::DEBUG_TYPE_DEPRECATED_BEHAVIOR,
    /// Something has invoked undefined behavior
    UndefinedBehavior = gl::DEBUG_TYPE_UNDEFINED_BEHAVIOR,
    /// Some functionality the user relies upon is not portable
    Portability = gl::DEBUG_TYPE_PORTABILITY,
    /// Code has triggered possible performance issues
    Performance = gl::DEBUG_TYPE_PERFORMANCE,
    /// Command stream annotation
    Marker = gl::DEBUG_TYPE_MARKER,
    ///
    PushGroup = gl::DEBUG_TYPE_PUSH_GROUP,
    ///
    PopGroup = gl::DEBUG_TYPE_POP_GROUP,
    ///
    Other = gl::DEBUG_TYPE_OTHER,
}

/// Allows you to obtain the timestamp inside the OpenGL commands queue.
///
/// When you call functions in glium, they are not instantly executed. Instead they are
/// added in a commands queue that the backend executes asynchronously.
///
/// When you call `TimestampQuery::new`, a command is added to this list asking the
/// backend to send us the current timestamp. Thanks to this, you can know how much time
/// it takes to execute commands.
///
/// ## Example
///
/// ```no_run
/// # let display: glium::Display = unsafe { std::mem::uninitialized() };
/// let before = glium::debug::TimestampQuery::new(&display);
/// // do some stuff here
/// let after = glium::debug::TimestampQuery::new(&display);
///
/// match (after, before) {
///     (Some(after), Some(before)) => {
///         let elapsed = after.get() - before.get();
///         println!("Time it took to do stuff: {}", elapsed);
///     },
///     _ => ()
/// }
/// ```
///
pub struct TimestampQuery {
    display: Display,
    id: gl::types::GLuint,
}

impl TimestampQuery {
    /// Creates a new `TimestampQuery`. Returns `None` if the backend doesn't support it.
    pub fn new(display: &Display) -> Option<TimestampQuery> {
        use std::mem;

        let (tx, rx) = channel();
        display.context.context.exec(move |: ctxt| {
            if ctxt.opengl_es || ctxt.version <= &context::GlVersion(3, 2) {    // TODO: extension
                tx.send(None);
                return;
            }

            unsafe {
                let mut id = mem::uninitialized();
                ctxt.gl.GenQueries(1, &mut id);
                tx.send(Some(id));

                ctxt.gl.QueryCounter(id, gl::TIMESTAMP);
            }
        });

        rx.recv().map(|q| TimestampQuery {
            display: display.clone(),
            id: q
        })
    }

    /// Queries to counter to see if the timestamp is already available.
    ///
    /// It takes some time to retreive the value, during which you can execute other
    /// functions.
    pub fn is_ready(&self) -> bool {
        use std::mem;

        let id = self.id.clone();
        let (tx, rx) = channel();
        self.display.context.context.exec(move |: ctxt| {
            unsafe {
                let mut value = mem::uninitialized();
                ctxt.gl.GetQueryObjectiv(id, gl::QUERY_RESULT_AVAILABLE, &mut value);
                tx.send(if value != 0 { true } else { false });
            }
        });

        rx.recv()
    }

    /// Returns the value of the timestamp. Blocks until it is available.
    ///
    /// This function doesn't block is `is_ready` returns true.
    pub fn get(self) -> u64 {
        use std::mem;

        let id = self.id.clone();
        let (tx, rx) = channel();
        self.display.context.context.exec(move |: ctxt| {
            unsafe {
                let mut value = mem::uninitialized();
                ctxt.gl.GetQueryObjectui64v(id, gl::QUERY_RESULT, &mut value);
                tx.send(value);
                ctxt.gl.DeleteQueries(1, [id].as_ptr())
            }
        });

        rx.recv()
    }
}
